version: '3.8'

services:
  vastvideo-go:
    image: ${DOCKER_NAMESPACE:-your-dockerhub-username}/vastvideo-go:${VERSION:-latest}
    container_name: vastvideo-go
    restart: unless-stopped
    ports:
      - "8228:8228"
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8228/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
